"""initial migration

Revision ID: 3c15a131b6e2
Revises: 
Create Date: 2026-06-27 13:05:03.388595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c15a131b6e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('feels_like', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('humidity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wind', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('condition', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('weather_code', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_column('weather_code')
        batch_op.drop_column('icon')
        batch_op.drop_column('condition')
        batch_op.drop_column('wind')
        batch_op.drop_column('humidity')
        batch_op.drop_column('feels_like')
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###
